### ISSUE TITLE
Require Function Isn't Defined

### ISSUE THREAD

**Issue by Zachary-Rude** [yzyzsun/PyJS#2]
You use the `require()` function in your JavaScript code, but you're not getting *any* errors (even though you aren't using Require.js), but, when I use that function (without loading Require.js), I get an error that says `require is not defined`! Why is it not happening for you without Require.js, but it *is* happening for me?

**Comment by yzyzsun** [comment]
The `require` function is part of [CommonJS](https://en.wikipedia.org/wiki/CommonJS), which is adopted by Node.js. If you want to use it in a place where `require` is unavailable (e.g. in a web browser), you probably want to bundle it using webpack first.

**Comment by Zachary-Rude** [comment]
I guess you *could* use Require.js, so that you can use the require() function
in a place where it is unavailable, especially in a web browser.

**Comment by yzyzsun** [comment]
Yes, we could. It's kind of personal taste. Since I need to bundle other stuff too, I prefer the webpack way in this case.
