### ISSUE TITLE
Is PyJS possible to use without Node.js via CDN

### ISSUE THREAD

**Issue by Sas2k** [yzyzsun/PyJS#3]
Hi, @yzyzsun. I'm thinking of using this on of my projects. Is it possible to use this without Node.js, Can I use this with like JSdelivr or any type cdn?

**Comment by Sas2k** [comment]
please do reply to this

**Comment by yzyzsun** [comment]
Of course, you can use it in a web browser without Node.js. The webpage `demo/index.html` is such an example and note that `demo/bundle.js` is generated from `demo.js` using webpack.

**Comment by Sas2k** [comment]
Ok, Thanks for your reply
